In [16]:
# Importing required packages
import numpy as np
from re import VERBOSE
import tensorflow as tf
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [3]:
# Create the document for this tutorial as reviews and sentiments
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [4]:
# Applying the one_hot function with vocabulary size 30
one_hot("amazing restaurant", 30)

[24, 12]

In [5]:
# One hot encode the complete reviews list as encoded_reviews
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[4, 15], [24, 12], [7, 4], [18, 11, 19], [9, 4, 2], [24, 15], [11, 4, 22], [3, 1], [3, 7], [20, 19]]


In [6]:
# To equal the length of sentences, we are padding the 2 word sentences into 3 word sentences
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[ 4 15  0]
 [24 12  0]
 [ 7  4  0]
 [18 11 19]
 [ 9  4  2]
 [24 15  0]
 [11  4 22]
 [ 3  1  0]
 [ 3  7  0]
 [20 19  0]]


In [7]:
# Separating the independent and dependent variable set
X = padded_reviews
y = sentiment

In [17]:
# Builod the model
embeded_vector_size = 5
vocab_size = 30
model = Sequential()
model.add(Embedding(30, 5 , input_length = 3, name = "embedding"))
model.add(Flatten())
model.add(Dense(1, activation = 'sigmoid'))

# Compile the model as follow
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Train the model using X and y with 50 epochs
model.fit(X, y, epochs = 50, verbose = 0)

In [18]:
# Get the model summary
print(model.summary())

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ (None, 3, 5)                │             150 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten_5 (Flatten)                  │ (None, 15)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 1)                   │              16 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 500 (1.96 KB)

 Trainable params: 166 (664.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 334 (1.31 KB)

None


In [19]:
# Get the weights matrix values associated with the embedding layer
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30