In [32]:
# Importing TensorFlow as tf and check its version
import tensorflow as tf
import matplotlib.pyplot as plt
tf.__version__

'2.17.0'

In [4]:
# Creating tensors of different data types
string = tf.Variable('I am Aniket', tf.string)
integer = tf.Variable(2001, tf.int32)
floating = tf.Variable(20.02, tf.float64)

# Check the rank of the string tensor
print(tf.rank(string))

# Check whether all three above tensors are of rank 0 or not
tf.rank(string) == tf.rank(integer) == tf.rank(floating)

tf.Tensor(0, shape=(), dtype=int32)


<tf.Tensor: shape=(), dtype=bool, numpy=True>

#### The above tensors have rank or degree equal to 0, also called as scalar quantity

In [6]:
# Creating tensors of higher dimensions
rank1_tensor = tf.Variable(['Test'], tf.string)
rank2_tensor = tf.Variable([['Test', 'Ok'], ['Test', 'Yes']], tf.string)

# Check the rank of the rank1_tensor and rank2_tensor
print('Rank of rank1_tensor is:', tf.rank(rank1_tensor))
print('Rank of rank2_tensor is:', tf.rank(rank2_tensor))

Rank of rank1_tensor is: tf.Tensor(1, shape=(), dtype=int32)
Rank of rank2_tensor is: tf.Tensor(2, shape=(), dtype=int32)


#### Rank 1 tensor is often called as a Vector. However, rank 2 tensor is called as a Matrix

In [7]:
# Determining the shape of a tensor. Also known as dimension of a tensor
# Get the shape of the string, integer, floting, rank1_tensor and rank2_tensor
print('Shape of the string tensor is:', string.shape)
print('Shape of the integer tensor is:', integer.shape)
print('Shape of the floating tensor is:', floating.shape)
print('Shape of the rank1_tensor tensor is:', rank1_tensor.shape)
print('Shape of the rank2_tensor tensor is:', rank2_tensor.shape) # Two ranks, and in each rank there is 2 elements

Shape of the string tensor is: ()
Shape of the integer tensor is: ()
Shape of the floating tensor is: ()
Shape of the rank1_tensor tensor is: (1,)
Shape of the rank2_tensor tensor is: (2, 2)


In [13]:
# Crete a tensor that is filled with ones of shape (1,2,3)
print('--------------Created the ones tensor------------------')
ones = tf.ones([1,2,3])
print(ones) # There is 1 internal list, 2 rows and 3 columns: in total 6 elements

# Get the rank of ones tensor
print('--------------Get the rank of ones tensor--------------')
print(tf.rank(ones))

# Convert the ones tensor into another tensor of shape (2,3,1): no. of elements remain same
print('-------Modify the ones tensor with (2,3,1) shape----------')
modified_ones = tf.reshape(ones, [2,3,1])
print(modified_ones) # There is 2 internal list, 3 rows and 1 column

# Get the rank of modified_ones tensor
print('-------------Get the rank of the first modified tensor-------------------')
print(tf.rank(modified_ones))

# Again modify the ones tensor using the shape (3,-1)
print('---------Modify the tensor one with (3,-1) shape -----------')
modified_ones_again = tf.reshape(ones, [3,-1]) # The notation [3,-1] tells that there will be 3 list, rest is upto the python
print(modified_ones_again) # This will reshape the tensor to (3*2)

# Get the rank of modified_ones_again tensor
print('-------------Get the rank of the second modified tensor-------------------')
print(tf.rank(modified_ones_again))

--------------Created the ones tensor------------------
tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
--------------Get the rank of ones tensor--------------
tf.Tensor(3, shape=(), dtype=int32)
-------Modify the ones tensor with (2,3,1) shape----------
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
-------------Get the rank of the first modified tensor-------------------
tf.Tensor(3, shape=(), dtype=int32)
---------Modify the tensor one with (3,-1) shape -----------
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
-------------Get the rank of the second modified tensor-------------------
tf.Tensor(2, shape=(), dtype=int32)


In [20]:
# Create a 1D tensor with entries ranges from (1,12) of float32 format
X = tf.range(12, dtype = tf.float32)
print('The tensor X is given as:', X)
print('Number of elements in X is:', tf.size(X))
print('Shape of tensor X is:', tf.shape(X))
print('Rank of tensor X is:', tf.rank(X))

The tensor X is given as: tf.Tensor([ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.], shape=(12,), dtype=float32)
Number of elements in X is: tf.Tensor(12, shape=(), dtype=int32)
Shape of tensor X is: tf.Tensor([12], shape=(1,), dtype=int32)
Rank of tensor X is: tf.Tensor(1, shape=(), dtype=int32)


In [22]:
# X conatisn  12 elements, reshape X to form X_reshape of shape (3,4)
X_reshape = tf.reshape(X, [3,4]) # [3,4] means 3 rows and 4 columns
print('The tensor X_reshape is given as:', X_reshape) # The same result can be obtained by specifying the shape parameter as [3,-1] or [1-,4]
print('Number of elements in X_reshape is:', tf.size(X_reshape))
print('Shape of tensor X_reshape is:', tf.shape(X_reshape))
print('Rank of tensor X_reshape is:', tf.rank(X_reshape))

The tensor X_reshape is given as: tf.Tensor(
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]], shape=(3, 4), dtype=float32)
Number of elements in X_reshape is: tf.Tensor(12, shape=(), dtype=int32)
Shape of tensor X_reshape is: tf.Tensor([3 4], shape=(2,), dtype=int32)
Rank of tensor X_reshape is: tf.Tensor(2, shape=(), dtype=int32)


In [27]:
# Create a 3D tensor y of zeroes having shape (2,3,4)
y = tf.zeros([2,3,4])
print('The tensor y is given as:', y) # A (3*4) matrix repeating 2 times
print('Shape of tensor y is:', tf.shape(y))
print('Rank of tensor y is:', tf.rank(y))
print('Number of elements in y is:', tf.size(y))

The tensor y is given as: tf.Tensor(
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]], shape=(2, 3, 4), dtype=float32)
Shape of tensor y is: tf.Tensor([2 3 4], shape=(3,), dtype=int32)
Rank of tensor y is: tf.Tensor(3, shape=(), dtype=int32)
Number of elements in y is: tf.Tensor(24, shape=(), dtype=int32)


In [33]:
# Create a tensor as T filled with elements having mean 0 and std 1 of shape (3*4)
T = tf.random.normal([3,4])
print('The tensor is given as:', T)
# tf.summary.histogram('Hist', T), to show the distribution

The tensor is given as: tf.Tensor(
[[-0.26155922 -2.4231188  -0.5716951   0.47251335]
 [ 0.79019356  0.8154709  -0.15964195 -2.2068133 ]
 [ 0.06495027  1.0119141  -0.00969734  0.26577258]], shape=(3, 4), dtype=float32)


In [34]:
# Create a constant tensor of manually defined entries
constant = tf.constant([[1,2,-5,3],[2,7,8,10],[-9,8,1,4],[3,5,6,1]])
constant

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 1,  2, -5,  3],
       [ 2,  7,  8, 10],
       [-9,  8,  1,  4],
       [ 3,  5,  6,  1]], dtype=int32)>

In [37]:
# Create a tensor called as data of shape (4,3,2) manually
# A (3*2) matrix repeating 4 times
# So, there will be 4 internal lists: each list contains 3 sublist: each sublist has 2 elements
data = tf.constant([[[74,128],[79,116],[71,119]], [[71,110],[78,118],[72,128]], [[84,138],[84,130],[74,120]], [[82,126],[76,156],[82,132]]])
data
# The shape (4,3,2) represents 0th axis, 1st axis and 2nd axis
# data can be used as: information about 2 features(2nd axis) of 3 patients(1st axis) at four different time stamps(0th axis)

<tf.Tensor: shape=(4, 3, 2), dtype=int32, numpy=
array([[[ 74, 128],
        [ 79, 116],
        [ 71, 119]],

       [[ 71, 110],
        [ 78, 118],
        [ 72, 128]],

       [[ 84, 138],
        [ 84, 130],
        [ 74, 120]],

       [[ 82, 126],
        [ 76, 156],
        [ 82, 132]]], dtype=int32)>

In [38]:
# Transposing the data tensor along the axis (1,0,2)
# So, the converted shape will be (3,4,2)
data_transpose = tf.transpose(data, perm = [1,0,2])
data_transpose # A (4*2) object repeating 3 times
# data_transpose: 3 patients (0th axis), 4 time stamps (1st axis), 2 features (2nd axis)

<tf.Tensor: shape=(3, 4, 2), dtype=int32, numpy=
array([[[ 74, 128],
        [ 71, 110],
        [ 84, 138],
        [ 82, 126]],

       [[ 79, 116],
        [ 78, 118],
        [ 84, 130],
        [ 76, 156]],

       [[ 71, 119],
        [ 72, 128],
        [ 74, 120],
        [ 82, 132]]], dtype=int32)>

In [46]:
# Define a tensor P with Variable method
P = tf.Variable([[1,2,5,-8],[2,1,7,-3]],dtype = tf.float32)
print('The tensor P is given as:',P)
P_exp = tf.exp(P)
print('The Exponentiated tensor P_exp is:', P_exp)

The tensor P is given as: <tf.Variable 'Variable:0' shape=(2, 4) dtype=float32, numpy=
array([[ 1.,  2.,  5., -8.],
       [ 2.,  1.,  7., -3.]], dtype=float32)>
The Exponentiated tensor P_exp is: tf.Tensor(
[[2.7182817e+00 7.3890562e+00 1.4841316e+02 3.3546262e-04]
 [7.3890562e+00 2.7182817e+00 1.0966332e+03 4.9787071e-02]], shape=(2, 4), dtype=float32)


In [47]:
# Define two tensors T1 and T2 and use mathematical operations on it
T1 = tf.constant([1.0,2,4,8])
T2 = tf.constant([2.0,2,2,2])
print('The tensor T1 is:', T1)
print('The tensor T2 is:', T2)

The tensor T1 is: tf.Tensor([1. 2. 4. 8.], shape=(4,), dtype=float32)
The tensor T2 is: tf.Tensor([2. 2. 2. 2.], shape=(4,), dtype=float32)


In [49]:
# Calculate mathematical operations on T1 and T2
T_sum = T1 + T2
T_diff = T1 - T2
T_mult = T1 * T2
T_div = T1 / T2
T_power = T1 ** T2
print('The Sum tensor will be:', T_sum)
print('The Difference tensor will be:', T_diff)
print('The Multiply tensor will be:', T_mult)
print('The Divide tensor will be:', T_div)
print('The power tensor will be:', T_power)

The Sum tensor will be: tf.Tensor([ 3.  4.  6. 10.], shape=(4,), dtype=float32)
The Difference tensor will be: tf.Tensor([-1.  0.  2.  6.], shape=(4,), dtype=float32)
The Multiply tensor will be: tf.Tensor([ 2.  4.  8. 16.], shape=(4,), dtype=float32)
The Divide tensor will be: tf.Tensor([0.5 1.  2.  4. ], shape=(4,), dtype=float32)
The power tensor will be: tf.Tensor([ 1.  4. 16. 64.], shape=(4,), dtype=float32)


In [57]:
# Create a tensor T3 of shape (3,4) with float32 dtype and entries in range (1,12)
T3 = tf.reshape(tf.range(12, dtype = tf.float32),(3,4))
print('The T3 tensor is given as:', T3)
# Define another tensor T4 with constant method of shape (3,4)
T4 = tf.constant([[2.0,1,4,3],[1.0,2,3,4],[4.0,3,2,1]])
print('The tensor T4 is given as:',T4)

The T3 tensor is given as: tf.Tensor(
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]], shape=(3, 4), dtype=float32)
The tensor T4 is given as: tf.Tensor(
[[2. 1. 4. 3.]
 [1. 2. 3. 4.]
 [4. 3. 2. 1.]], shape=(3, 4), dtype=float32)


In [58]:
# Concatinate operation on T3 and T4 top-bottom and left-right
print('------ Top bottom Concatenate----------------')
T5 = tf.concat([T3,T4], axis = 0) # Axis = 0 is top-bottom
print('Top-bottom concatenate operation result:', T5)
print('------ Left Right Concatenate----------------')
T6 = tf.concat([T3,T4], axis = 1) # Axis = 0 is left-right
print('Left-right concatenate operation result:', T6)

------ Top bottom Concatenate----------------
Top-bottom concatenate operation result: tf.Tensor(
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [ 2.  1.  4.  3.]
 [ 1.  2.  3.  4.]
 [ 4.  3.  2.  1.]], shape=(6, 4), dtype=float32)
------ Left Right Concatenate----------------
Left-right concatenate operation result: tf.Tensor(
[[ 0.  1.  2.  3.  2.  1.  4.  3.]
 [ 4.  5.  6.  7.  1.  2.  3.  4.]
 [ 8.  9. 10. 11.  4.  3.  2.  1.]], shape=(3, 8), dtype=float32)


In [59]:
# Check if corresponding elements match
print(T3 == T4) # Returns True if corresponding elements match

tf.Tensor(
[[False  True False  True]
 [False False False False]
 [False False False False]], shape=(3, 4), dtype=bool)


In [64]:
# Summing all the entries of a tensor
# Sum the entries of T4 tensor
print('-----------The T4 tensor is given as-----------')
print(T4)
print('-----------------The scalar one term sum of T4 is-----------------')
print(tf.reduce_sum(T4))
print('-----------------Top bottom sum of T4 is -----------------------')
print(tf.reduce_sum(T4, axis  = 0))
print('-----------------Left Right sum of T4 is -----------------------')
print(tf.reduce_sum(T4, axis  = 1))

-----------The T4 tensor is given as-----------
tf.Tensor(
[[2. 1. 4. 3.]
 [1. 2. 3. 4.]
 [4. 3. 2. 1.]], shape=(3, 4), dtype=float32)
-----------------The scalar one term sum of T4 is-----------------
tf.Tensor(30.0, shape=(), dtype=float32)
-----------------Top bottom sum of T4 is -----------------------
tf.Tensor([7. 6. 9. 8.], shape=(4,), dtype=float32)
-----------------Left Right sum of T4 is -----------------------
tf.Tensor([10. 10. 10.], shape=(3,), dtype=float32)


In [65]:
# Calculating the average of all the entries of a tensor
# Average of all the entries of T4 tensor
print('-----------The T4 tensor is given as-----------')
print(T4)
print('-----------------Average of entries of T4 is-----------------')
print(tf.math.reduce_mean(T4))
print('-----------------Top bottom average of T4 is -----------------------')
print(tf.math.reduce_mean(T4, axis  = 0))
print('-----------------Left Right average of T4 is -----------------------')
print(tf.math.reduce_mean(T4, axis  = 1))

-----------The T4 tensor is given as-----------
tf.Tensor(
[[2. 1. 4. 3.]
 [1. 2. 3. 4.]
 [4. 3. 2. 1.]], shape=(3, 4), dtype=float32)
-----------------Average of entries of T4 is-----------------
tf.Tensor(2.5, shape=(), dtype=float32)
-----------------Top bottom average of T4 is -----------------------
tf.Tensor([2.3333333 2.        3.        2.6666667], shape=(4,), dtype=float32)
-----------------Left Right average of T4 is -----------------------
tf.Tensor([2.5 2.5 2.5], shape=(3,), dtype=float32)
