In [2]:
import tensorflow as tf

In [3]:
# Checking version
tf.__version__

'2.15.0'

In [7]:
# Constructing a constant tensor
T = tf.constant([[[74, 128], [79, 116], [71, 116]],
              [[78, 118], [82, 124], [72, 128]],
              [[84, 138], [84, 130], [74, 120]],
              [[82, 126], [76, 156], [82, 132]]])
print(T.shape)
print(T) # It is a (3*2) object repreating 4 times

(4, 3, 2)
tf.Tensor(
[[[ 74 128]
  [ 79 116]
  [ 71 116]]

 [[ 78 118]
  [ 82 124]
  [ 72 128]]

 [[ 84 138]
  [ 84 130]
  [ 74 120]]

 [[ 82 126]
  [ 76 156]
  [ 82 132]]], shape=(4, 3, 2), dtype=int32)


In [10]:
# Transposing this tensor
T_tran = tf.transpose(T, perm = [1,0,2])
print(T_tran.shape) # It is a (4*2) object repeating 3 times
print(T_tran)

(3, 4, 2)
tf.Tensor(
[[[ 74 128]
  [ 78 118]
  [ 84 138]
  [ 82 126]]

 [[ 79 116]
  [ 82 124]
  [ 84 130]
  [ 76 156]]

 [[ 71 116]
  [ 72 128]
  [ 74 120]
  [ 82 132]]], shape=(3, 4, 2), dtype=int32)


In [12]:
# Using Reduce_sum on T_Tran
T_sum0 = tf.reduce_sum(T_tran, axis = 0)
T_sum0
# The first element of T_sum0 is sum of first entries of each (4*2) object

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[224, 360],
       [232, 370],
       [242, 388],
       [240, 414]], dtype=int32)>

In [14]:
print(T_tran.shape)
print(T_tran)

(3, 4, 2)
tf.Tensor(
[[[ 74 128]
  [ 78 118]
  [ 84 138]
  [ 82 126]]

 [[ 79 116]
  [ 82 124]
  [ 84 130]
  [ 76 156]]

 [[ 71 116]
  [ 72 128]
  [ 74 120]
  [ 82 132]]], shape=(3, 4, 2), dtype=int32)


In [13]:
# Mean of T_tran
T_mean0 = tf.reduce_mean(T_tran, axis = 0)
T_mean0

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 74, 120],
       [ 77, 123],
       [ 80, 129],
       [ 80, 138]], dtype=int32)>

In [15]:
print(T_tran.shape)
print(T_tran)

(3, 4, 2)
tf.Tensor(
[[[ 74 128]
  [ 78 118]
  [ 84 138]
  [ 82 126]]

 [[ 79 116]
  [ 82 124]
  [ 84 130]
  [ 76 156]]

 [[ 71 116]
  [ 72 128]
  [ 74 120]
  [ 82 132]]], shape=(3, 4, 2), dtype=int32)


In [16]:
T_sum1 = tf.reduce_sum(T_tran, axis = 1)
T_sum1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[318, 510],
       [321, 526],
       [299, 496]], dtype=int32)>

In [17]:
print(T_tran.shape)
print(T_tran)

(3, 4, 2)
tf.Tensor(
[[[ 74 128]
  [ 78 118]
  [ 84 138]
  [ 82 126]]

 [[ 79 116]
  [ 82 124]
  [ 84 130]
  [ 76 156]]

 [[ 71 116]
  [ 72 128]
  [ 74 120]
  [ 82 132]]], shape=(3, 4, 2), dtype=int32)


In [19]:
T_mean1 = tf.reduce_mean(T_tran, axis = 1)
T_mean1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 79, 127],
       [ 80, 131],
       [ 74, 124]], dtype=int32)>